### ISSUE TITLE
请问如何给post设置cover

### ISSUE THREAD

**Issue by alanzeng423** [myyerrol/hexo-theme-freemind-plus#1]
我正在使用freemind-plus主题，请问如何给post设置cover

**Comment by alanzeng423** [comment]
@myyerrol

**Comment by myyerrol** [comment]
您好，您指的【给post设置cover】是需要给文章添加封面图吗？如果是的话，可以在文章的front-matter中添加**feature**属性并在其后放置图片链接即可。如果不是的话，最好能给一个更加详细的描述或示例，谢谢。

**Comment by alanzeng423** [comment]
是的，我尝试了在font-matter添加照片链接如：

```
feature: images/my_img.jpg
```
或
```
feature: https://my_img_url
```

但封面图片未能正常加载，查看图片链接发现与该篇博客的链接发生了拼接，比如
`https://myblog.com/blogs/.../images/my_img.jpg`

我经过尝试没能解决这个问题，请问您是否遇到过类似情况或您是否知道如何解决，如果可以，那对我来说是莫大的帮助，谢谢☺️

**Comment by myyerrol** [comment]
好的，我晚上找时间看下。

**Comment by myyerrol** [comment]
看了下主题的源码，发现如果在`_config.yml`文件中开启了`post_asset_folder`选项，Hexo在渲染的时候就会给图片地址前添加路径前缀，这个功能官网[文档](https://hexo.io/zh-cn/docs/asset-folders)中有介绍。如果想通过图床使用外链的话，把这个选项关闭即可。

![屏幕截图 2024-10-24 182857](https://github.com/user-attachments/assets/e8f74c96-3173-4ef0-919c-89ab50d8d10b)

**Comment by alanzeng423** [comment]
解决了，万分感谢
